/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gstbilling.admin;

import gstbilling.Connect;
import static gstbilling.Connect.connect;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Rishabh
 */
public class GstCompanyDetail extends javax.swing.JInternalFrame {

    /**
     * Creates new form GstClassificationDetail
     */
    
    private static String applicablefrom;
        
    public GstCompanyDetail() {
        initComponents();
         try{
             Connection con=Connect.connect();
             PreparedStatement ps=con.prepareStatement("Select * from companydetail");
             ResultSet rs=ps.executeQuery();
             if(rs.next())
             {
                  
                  jcompanyname.setText(rs.getString("companyname"));
                  jCombostate.setSelectedItem(rs.getString("state"));
                   jComboRegistration.setSelectedItem(rs.getString("registrationtype"));
                    jgstin.setText(rs.getString("gstinnumber"));
                    applicablefrom=rs.getString("applicablefrom").toString();
                    String ac[]=new String[3];
                     ac=applicablefrom.split("-");
                     jComboyear.setSelectedItem(ac[0]);
                     jCombomonth.setSelectedItem(ac[1]);
                     jCombodate.setSelectedItem(ac[2]);
                     jpan.setText(rs.getString("pannumber"));
                     jcinnumber.setText(rs.getString("cinnumber"));
             }
             
        
        }catch(Exception ex){}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jupdatebutton = new javax.swing.JButton();
        jcompanyname = new javax.swing.JTextField();
        jCombostate = new javax.swing.JComboBox();
        jComboRegistration = new javax.swing.JComboBox();
        jgstin = new javax.swing.JTextField();
        jCombodate = new javax.swing.JComboBox();
        jCombomonth = new javax.swing.JComboBox();
        jComboyear = new javax.swing.JComboBox();
        jpan = new javax.swing.JTextField();
        jcinnumber = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setTitle("GST COMPANY DETAIL");

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel6.setText("PAN Number");

        jLabel7.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel7.setText("GST COMPANY DETAIL");

        jLabel8.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel8.setText("Corporate Identity Number");

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel1.setText("State");

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel2.setText("Company Name");

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel3.setText("Registration Type");

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel4.setText("GSTIN/UIN No");

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel5.setText("Applicable From");

        jupdatebutton.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jupdatebutton.setText("Update");
        jupdatebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jupdatebuttonActionPerformed(evt);
            }
        });

        jcompanyname.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jcompanyname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcompanynameActionPerformed(evt);
            }
        });

        jCombostate.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jCombostate.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Andra Pradesh", "Arunachal Pradesh", "Assam", "Bihar", "Chhattisgarh", "Goa", "Gujarat", "Haryana", "Himachal Pradesh", "Jammu and Kashmir", "Jharkhand", "Karnataka", "Kerala", "Madya Pradesh", "Maharashtra", "Manipur", "Meghalaya", "Mizoram", "Nagaland", "Orissa", "Punjab", "Rajasthan", "Sikkim", "Tamil Nadu", "Tripura", "Uttaranchal", "Uttar Pradesh", "West Bengal" }));
        jCombostate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCombostateActionPerformed(evt);
            }
        });

        jComboRegistration.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jComboRegistration.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Composite Dealer", "Regular Dealer", "Input Service distributer", "Unregistered Dealer", "E-commerce operator", "Foreign non-resident taxpayer", "Unknown" }));

        jgstin.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N

        jCombodate.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jCombodate.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Date", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jCombomonth.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jCombomonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Month", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        jComboyear.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jComboyear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Year", "2017", "2018", "2019", "2020" }));

        jpan.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N

        jcinnumber.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jCombostate, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboRegistration, 0, 255, Short.MAX_VALUE)
                            .addComponent(jgstin)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCombodate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCombomonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jpan)
                            .addComponent(jcinnumber)
                            .addComponent(jcompanyname)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jupdatebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcompanyname, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCombostate, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jgstin, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCombodate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCombomonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpan, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcinnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jupdatebutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(68, 68, 68))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcompanynameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcompanynameActionPerformed
       
        
    }//GEN-LAST:event_jcompanynameActionPerformed

    private void jCombostateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCombostateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCombostateActionPerformed

    private void jupdatebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jupdatebuttonActionPerformed
        // TODO add your handling code here:
        try{
            Connection con=Connect.connect();
            PreparedStatement ps=con.prepareStatement("Update companydetail set companyname=? , state=? , registrationtype=? , gstinnumber=? , applicablefrom=? , pannumber=? , cinnumber=? , modifieddate=now() " );
            ps.setString(1,jcompanyname.getText());
            ps.setString(2,jCombostate.getSelectedItem().toString());
            ps.setString(3,jComboRegistration.getSelectedItem().toString());
            ps.setString(4, jgstin.getText());
          
            String calender=jComboyear.getSelectedItem().toString()+"-"+jCombomonth.getSelectedItem().toString()+"-"+jCombodate.getSelectedItem().toString();
            Date dd=Date.valueOf(calender);
            ps.setString(5, dd.toString());
            ps.setString(6,jpan.getText());
            ps.setString(7, jcinnumber.getText());
            int a=ps.executeUpdate();
            if(a>0)
            {JOptionPane.showMessageDialog(this, "SUCCESSFULLY CHANGED SEE EFFECT BY RELOGIN","Information Message",JOptionPane.INFORMATION_MESSAGE);
            }
            else
                JOptionPane.showMessageDialog(this, "RECHANGED SOME ERROR OCCUR","Information Message",JOptionPane.INFORMATION_MESSAGE);
          
                
        }
        catch(Exception exe)
        {JOptionPane.showMessageDialog(this, "Error"+exe,"Information Message",JOptionPane.INFORMATION_MESSAGE);  }
        
    }//GEN-LAST:event_jupdatebuttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboRegistration;
    private javax.swing.JComboBox jCombodate;
    private javax.swing.JComboBox jCombomonth;
    private javax.swing.JComboBox jCombostate;
    private javax.swing.JComboBox jComboyear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jcinnumber;
    private javax.swing.JTextField jcompanyname;
    private javax.swing.JTextField jgstin;
    private javax.swing.JTextField jpan;
    private javax.swing.JButton jupdatebutton;
    // End of variables declaration//GEN-END:variables
}
